all: performance_compare QuadR-Tree_Perf RLinear_Perf RStar_Perf

performance_compare: ./Performance\ Tests/performance_compare.cpp
	g++ ./Performance\ Tests/performance_compare.cpp -o performance_compare

QuadR-Tree_Perf: ./Performance\ Tests/QuadR-Tree_Perf.cpp
	g++ ./Performance\ Tests/QuadR-Tree_Perf.cpp -o QuadR-Tree_Perf

RLinear_Perf: ./Performance\ Tests/RLinear_Perf.cpp
	g++ ./Performance\ Tests/RLinear_Perf.cpp -o RLinear_Perf

RStar_Perf: ./Performance\ Tests/RStar_Perf.cpp
	g++ ./Performance\ Tests/RStar_Perf.cpp -o RStar_Perf